version: '3'
services:
  ci-node-server:
    restart: always
    env_file: ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
        - ./server:/app
        - /app/node_modules
    ports:
        - 5000:5000
        - 9229:9229
  ci-client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '3000:80'
