version: '3'
services:
  api:
    restart: always
    env_file: ./.env
    build:
      context: ./server
    ports:
      - 3000:3000
  client:
      restart: always
      build:
        context: ./client
      volumes:
        - ./client:/app
      ports:
        - 8000:3000
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'