version: '3'
services:
  ci-node-server:
    restart: always
    env_file: ./server/.env
    build:
      context: ./server
    ports:
      - 5000:5000
  ci-client:
      restart: always
      build:
        context: ./client
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '3000:80'