version: '3'
services:
  api:
    restart: always
    env_file: ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
        - ./server:/app
    ports:
        - 8900:5000
        - 9229:9229
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    ports:
      - 8800:3000
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
